// <auto-generated />
namespace pblsh.giraffe.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open pblsh.giraffe

[<DbContext(typeof<Identity.ApplicationDbContext>)>]
type ApplicationDbContextModelSnapshot() =
    inherit ModelSnapshot()

    override this.BuildModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.29")
            .HasAnnotation("Relational:MaxIdentifierLength", 128) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", (fun b ->

            b.Property<string>("Id")
                .IsRequired(true)
                .HasColumnType("nvarchar(450)")
                |> ignore

            b.Property<string>("ConcurrencyStamp")
                .IsConcurrencyToken()
                .IsRequired(true)
                .HasColumnType("nvarchar(max)")
                |> ignore

            b.Property<string>("Name")
                .IsRequired(true)
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)")
                |> ignore

            b.Property<string>("NormalizedName")
                .IsRequired(true)
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)")
                |> ignore

            b.HasKey("Id")
                |> ignore


            b.HasIndex("NormalizedName")
                .IsUnique()
                .HasDatabaseName("RoleNameIndex")
                .HasFilter("[NormalizedName] IS NOT NULL") |> ignore

            b.ToTable("AspNetRoles") |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", (fun b ->

            b.Property<int>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                |> ignore

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1) |> ignore

            b.Property<string>("ClaimType")
                .IsRequired(true)
                .HasColumnType("nvarchar(max)")
                |> ignore

            b.Property<string>("ClaimValue")
                .IsRequired(true)
                .HasColumnType("nvarchar(max)")
                |> ignore

            b.Property<string>("RoleId")
                .IsRequired(true)
                .HasColumnType("nvarchar(450)")
                |> ignore

            b.HasKey("Id")
                |> ignore


            b.HasIndex("RoleId")
                |> ignore

            b.ToTable("AspNetRoleClaims") |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", (fun b ->

            b.Property<string>("Id")
                .IsRequired(true)
                .HasColumnType("nvarchar(450)")
                |> ignore

            b.Property<int>("AccessFailedCount")
                .IsRequired(true)
                .HasColumnType("int")
                |> ignore

            b.Property<string>("ConcurrencyStamp")
                .IsConcurrencyToken()
                .IsRequired(true)
                .HasColumnType("nvarchar(max)")
                |> ignore

            b.Property<string>("Email")
                .IsRequired(true)
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)")
                |> ignore

            b.Property<bool>("EmailConfirmed")
                .IsRequired(true)
                .HasColumnType("bit")
                |> ignore

            b.Property<bool>("LockoutEnabled")
                .IsRequired(true)
                .HasColumnType("bit")
                |> ignore

            b.Property<Nullable<DateTimeOffset>>("LockoutEnd")
                .IsRequired(false)
                .HasColumnType("datetimeoffset")
                |> ignore

            b.Property<string>("NormalizedEmail")
                .IsRequired(true)
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)")
                |> ignore

            b.Property<string>("NormalizedUserName")
                .IsRequired(true)
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)")
                |> ignore

            b.Property<string>("PasswordHash")
                .IsRequired(true)
                .HasColumnType("nvarchar(max)")
                |> ignore

            b.Property<string>("PhoneNumber")
                .IsRequired(true)
                .HasColumnType("nvarchar(max)")
                |> ignore

            b.Property<bool>("PhoneNumberConfirmed")
                .IsRequired(true)
                .HasColumnType("bit")
                |> ignore

            b.Property<string>("SecurityStamp")
                .IsRequired(true)
                .HasColumnType("nvarchar(max)")
                |> ignore

            b.Property<bool>("TwoFactorEnabled")
                .IsRequired(true)
                .HasColumnType("bit")
                |> ignore

            b.Property<string>("UserName")
                .IsRequired(true)
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)")
                |> ignore

            b.HasKey("Id")
                |> ignore


            b.HasIndex("NormalizedEmail")
                .HasDatabaseName("EmailIndex") |> ignore


            b.HasIndex("NormalizedUserName")
                .IsUnique()
                .HasDatabaseName("UserNameIndex")
                .HasFilter("[NormalizedUserName] IS NOT NULL") |> ignore

            b.ToTable("AspNetUsers") |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", (fun b ->

            b.Property<int>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                |> ignore

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1) |> ignore

            b.Property<string>("ClaimType")
                .IsRequired(true)
                .HasColumnType("nvarchar(max)")
                |> ignore

            b.Property<string>("ClaimValue")
                .IsRequired(true)
                .HasColumnType("nvarchar(max)")
                |> ignore

            b.Property<string>("UserId")
                .IsRequired(true)
                .HasColumnType("nvarchar(450)")
                |> ignore

            b.HasKey("Id")
                |> ignore


            b.HasIndex("UserId")
                |> ignore

            b.ToTable("AspNetUserClaims") |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", (fun b ->

            b.Property<string>("LoginProvider")
                .IsRequired(true)
                .HasColumnType("nvarchar(450)")
                |> ignore

            b.Property<string>("ProviderKey")
                .IsRequired(true)
                .HasColumnType("nvarchar(450)")
                |> ignore

            b.Property<string>("ProviderDisplayName")
                .IsRequired(true)
                .HasColumnType("nvarchar(max)")
                |> ignore

            b.Property<string>("UserId")
                .IsRequired(true)
                .HasColumnType("nvarchar(450)")
                |> ignore

            b.HasKey("LoginProvider", "ProviderKey")
                |> ignore


            b.HasIndex("UserId")
                |> ignore

            b.ToTable("AspNetUserLogins") |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", (fun b ->

            b.Property<string>("UserId")
                .IsRequired(true)
                .HasColumnType("nvarchar(450)")
                |> ignore

            b.Property<string>("RoleId")
                .IsRequired(true)
                .HasColumnType("nvarchar(450)")
                |> ignore

            b.HasKey("UserId", "RoleId")
                |> ignore


            b.HasIndex("RoleId")
                |> ignore

            b.ToTable("AspNetUserRoles") |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", (fun b ->

            b.Property<string>("UserId")
                .IsRequired(true)
                .HasColumnType("nvarchar(450)")
                |> ignore

            b.Property<string>("LoginProvider")
                .IsRequired(true)
                .HasColumnType("nvarchar(450)")
                |> ignore

            b.Property<string>("Name")
                .IsRequired(true)
                .HasColumnType("nvarchar(450)")
                |> ignore

            b.Property<string>("Value")
                .IsRequired(true)
                .HasColumnType("nvarchar(max)")
                |> ignore

            b.HasKey("UserId", "LoginProvider", "Name")
                |> ignore


            b.ToTable("AspNetUserTokens") |> ignore

        )) |> ignore
        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", (fun b ->
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                .WithMany()
                .HasForeignKey("RoleId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                |> ignore

        )) |> ignore
        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", (fun b ->
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                |> ignore

        )) |> ignore
        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", (fun b ->
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                |> ignore

        )) |> ignore
        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", (fun b ->
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                .WithMany()
                .HasForeignKey("RoleId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                |> ignore
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                |> ignore

        )) |> ignore
        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", (fun b ->
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                |> ignore

        )) |> ignore

